Repository Zoo-Goorm/Zoo-Backend, pull requests merged in 2025-03, with the labels that each got.

#6 fix: application.yml 전환
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: 💡 rename, ✏️ style

#10 [#9] Redis 설정
  build.gradle
  src/main/java/zoo/insightnote/global/config/RedisConfig.java
  src/main/resources/application.yml
Labels: ⚙ build, ✨ feat

#12 [#2] 컨벤션 CRUD + S3 presigned URL 적용
  build.gradle
  src/main/java/zoo/insightnote/domain/event/controller/EventController.java
  src/main/java/zoo/insightnote/domain/event/controller/EventControllerImpl.java
  src/main/java/zoo/insightnote/domain/event/dto/req/EventRequestDto.java
  src/main/java/zoo/insightnote/domain/event/dto/req/EventUpdateRequestDto.java
  src/main/java/zoo/insightnote/domain/event/dto/res/EventResponseDto.java
  src/main/java/zoo/insightnote/domain/event/entity/Event.java
  src/main/java/zoo/insightnote/domain/event/service/EventService.java
  src/main/java/zoo/insightnote/domain/image/entity/EntityType.java
  src/main/java/zoo/insightnote/domain/image/entity/Image.java
  src/main/java/zoo/insightnote/domain/image/repository/ImageRepository.java
  src/main/java/zoo/insightnote/domain/image/service/ImageService.java
  src/main/java/zoo/insightnote/domain/s3/controller/S3Controller.java
  src/main/java/zoo/insightnote/domain/s3/controller/S3ControllerImpl.java
  src/main/java/zoo/insightnote/domain/s3/service/S3Service.java
  src/main/java/zoo/insightnote/global/config/S3Config.java
  src/main/java/zoo/insightnote/global/config/SwaggerConfig.java
  src/main/java/zoo/insightnote/global/entity/BaseTimeEntity.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/zoo/insightnote/domain/event/service/EventServiceTest.java
Labels: ✨ feat

#11 [#3] 카카오페이 API 연동
  src/main/java/zoo/insightnote/InsightNoteApplication.java
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentController.java
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentControllerImpl.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/AmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/CardInfoDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentApproveRequestDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentRequestReadyDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayApproveResponseDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayReadyResponseDto.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
  src/main/resources/application.yml
Labels: ✨ feat

#13 [#8] 인사이트 노트 대댓글 기능 개발
  build.gradle
  src/main/java/zoo/insightnote/domain/comment/service/CommentService.java
  src/main/java/zoo/insightnote/domain/reply/controller/ReplyController.java
  src/main/java/zoo/insightnote/domain/reply/controller/ReplyControllerImpl.java
  src/main/java/zoo/insightnote/domain/reply/dto/ReplyRequest.java
  src/main/java/zoo/insightnote/domain/reply/dto/ReplyResponse.java
  src/main/java/zoo/insightnote/domain/reply/entity/Reply.java
  src/main/java/zoo/insightnote/domain/reply/mapper/ReplyMapper.java
  src/main/java/zoo/insightnote/domain/reply/repository/ReplyRepository.java
  src/main/java/zoo/insightnote/domain/reply/service/ReplyService.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
  src/main/resources/application.yml
  src/test/java/zoo/insightnote/domain/comment/service/CommentServiceTest.java
  src/test/java/zoo/insightnote/domain/reply/service/ReplyServiceTest.java
Labels: ✨ feat

#18 [#17] insightNote 기본 CRUD 구현
  src/main/java/zoo/insightnote/domain/insight/controller/InsightController.java
  src/main/java/zoo/insightnote/domain/insight/controller/InsightControllerImpl.java
  src/main/java/zoo/insightnote/domain/insight/dto/InsightRequestDto.java
  src/main/java/zoo/insightnote/domain/insight/dto/InsightResponseDto.java
  src/main/java/zoo/insightnote/domain/insight/entity/Insight.java
  src/main/java/zoo/insightnote/domain/insight/mapper/InsightMapper.java
  src/main/java/zoo/insightnote/domain/insight/service/InsightService.java
  src/main/java/zoo/insightnote/domain/session/entity/Session.java
  src/main/java/zoo/insightnote/domain/session/mapper/SessionMapper.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
Labels: ✨ feat

#21 [#4] 소셜 로그인 구현 완료
  build.gradle
  src/main/java/zoo/insightnote/domain/user/dto/CustomOAuth2User.java
  src/main/java/zoo/insightnote/domain/user/dto/GoogleResponse.java
  src/main/java/zoo/insightnote/domain/user/dto/KakaoResponse.java
  src/main/java/zoo/insightnote/domain/user/dto/OAuth2Response.java
  src/main/java/zoo/insightnote/domain/user/dto/UserDto.java
  src/main/java/zoo/insightnote/domain/user/entity/AuthProvider.java
  src/main/java/zoo/insightnote/domain/user/entity/Role.java
  src/main/java/zoo/insightnote/domain/user/entity/User.java
  src/main/java/zoo/insightnote/domain/user/repository/UserRepository.java
  src/main/java/zoo/insightnote/domain/user/service/CustomOAuth2UserService.java
  src/main/java/zoo/insightnote/global/config/CorsMvcConfig.java
  src/main/java/zoo/insightnote/global/config/SecurityConfig.java
  src/main/java/zoo/insightnote/global/jwt/JWTFilter.java
  src/main/java/zoo/insightnote/global/jwt/JWTUtil.java
  src/main/java/zoo/insightnote/global/oauth2/CustomSuccessHandler.java
  src/main/resources/application-oauth.yml
  src/main/resources/application.yml
Labels: ✨ feat

#24 [#16] 결제 내역, 예약 세션 저장
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentControllerImpl.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/AmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/CardInfoDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentRequestReadyDto.java
  src/main/java/zoo/insightnote/domain/payment/entity/Payment.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/reservation/entity/Reservation.java
Labels: ✨ feat

#31 [#30] Payment Swagger 적용
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentController.java
Labels: 📘 docs

#23 [#19] 세션 페이지, 참가 페이지용 GET API 추가
  src/main/java/zoo/insightnote/domain/image/entity/Image.java
  src/main/java/zoo/insightnote/domain/image/service/ImageService.java
  src/main/java/zoo/insightnote/domain/insight/dto/InsightResponseDto.java
  src/main/java/zoo/insightnote/domain/insight/mapper/InsightMapper.java
  src/main/java/zoo/insightnote/domain/keyword/dto/KeywordResponseDto.java
  src/main/java/zoo/insightnote/domain/keyword/entity/Keyword.java
  src/main/java/zoo/insightnote/domain/keyword/mapper/KeywordMapper.java
  src/main/java/zoo/insightnote/domain/keyword/repository/KeywordRepository.java
  src/main/java/zoo/insightnote/domain/keyword/service/KeywordService.java
  src/main/java/zoo/insightnote/domain/session/controller/SessionController.java
  src/main/java/zoo/insightnote/domain/session/controller/SessionControllerImpl.java
  src/main/java/zoo/insightnote/domain/session/dto/SessionRequest.java
  src/main/java/zoo/insightnote/domain/session/dto/SessionRequestDto.java
  src/main/java/zoo/insightnote/domain/session/dto/SessionResponse.java
  src/main/java/zoo/insightnote/domain/session/dto/SessionResponseDto.java
  src/main/java/zoo/insightnote/domain/session/entity/Session.java
  src/main/java/zoo/insightnote/domain/session/mapper/SessionMapper.java
  src/main/java/zoo/insightnote/domain/session/repository/SessionRepository.java
  src/main/java/zoo/insightnote/domain/session/service/SessionService.java
  src/main/java/zoo/insightnote/domain/sessionKeyword/entity/SessionKeyword.java
  src/main/java/zoo/insightnote/domain/sessionKeyword/repository/SessionKeywordRepository.java
  src/main/java/zoo/insightnote/domain/sessionKeyword/service/SessionKeywordService.java
  src/main/java/zoo/insightnote/global/entity/BaseTimeEntity.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
  src/test/java/zoo/insightnote/domain/session/service/SessionServiceTest.java
Labels: ✨ feat

#39 [#35] 결제 시 유저 정보 저장 로직 구현
  .github/workflows/CICD.yml
  src/main/java/zoo/insightnote/domain/payment/dto/etc/UserInfoDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentRequestReadyDto.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/user/entity/User.java
  src/main/java/zoo/insightnote/domain/user/repository/UserRepository.java
Labels: ✨ feat

#45 fix : INSERT INGORE를 추가하여 데이터 중복을 방지
  src/main/resources/data.sql
Labels: 🔨fix

#48 [#47] jwt 관련 추가 설정
  src/main/java/zoo/insightnote/global/jwt/JWTFilter.java
  src/main/java/zoo/insightnote/global/oauth2/CustomSuccessHandler.java
Labels: ✨ feat

#54 [#46] 소지 티켓, 예약 세션 반환 API 구현
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationController.java
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationControllerImpl.java
  src/main/java/zoo/insightnote/domain/reservation/dto/response/UserTicketInfoResponseDto.java
  src/main/java/zoo/insightnote/domain/reservation/entity/Reservation.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationCustomQueryRepository.java
  src/main/java/zoo/insightnote/domain/reservation/service/ReservationService.java
  src/main/java/zoo/insightnote/domain/session/dto/SessionRequestDto.java
  src/main/java/zoo/insightnote/domain/session/entity/Session.java
  src/main/java/zoo/insightnote/global/config/QuerydslConfig.java
  src/main/resources/data.sql
Labels: ✨ feat

#62 [#61] feat: 모니터링 툴 추가 (Prometheus, Grafana)
  build.gradle
Labels: ⚙ build

#66 [#57] 세션 신청, 취소, 취소 후 신청 API 구현
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationController.java
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationControllerImpl.java
  src/main/java/zoo/insightnote/domain/reservation/entity/Reservation.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationRepository.java
  src/main/java/zoo/insightnote/domain/reservation/service/ReservationService.java
  src/main/java/zoo/insightnote/domain/session/repository/SessionRepository.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
Labels: ✨ feat

#70 [#67] Payment, Reservation Username 적용
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentController.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationController.java
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationControllerImpl.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationCustomQueryRepository.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationRepository.java
  src/main/java/zoo/insightnote/domain/reservation/service/ReservationService.java
  src/main/java/zoo/insightnote/domain/session/repository/SessionRepository.java
  src/main/java/zoo/insightnote/domain/session/service/SessionService.java
Labels: ✨ feat

#73 [#72] Payment 참가자 신청 정보 구현
  src/main/java/zoo/insightnote/domain/payment/dto/etc/UserInfoDto.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/user/entity/User.java
Labels: ✨ feat

#76 [#75] User 정보 반환 API 구현
  src/main/java/zoo/insightnote/domain/user/controller/UserController.java
  src/main/java/zoo/insightnote/domain/user/controller/UserControllerImpl.java
  src/main/java/zoo/insightnote/domain/user/dto/PaymentUserInfoResponseDto.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
Labels: ✨ feat

#80 build : CI/CD 파일 수정 및 배포 스크립트 추가
  .github/workflows/CICD.yml
  scripts/after_install.sh
  scripts/appspec.yml
  scripts/deploy.sh
  scripts/stop.sh
  src/main/java/zoo/insightnote/global/config/CorsMvcConfig.java
  src/main/java/zoo/insightnote/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: ⚙ build

#82 [#74] QR 생성, 인식 API 구현
  build.gradle
  src/main/java/zoo/insightnote/domain/payment/entity/Payment.java
  src/main/java/zoo/insightnote/domain/payment/repository/PaymentRepository.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/qr/controller/QrController.java
  src/main/java/zoo/insightnote/domain/qr/controller/QrControllerImpl.java
  src/main/java/zoo/insightnote/domain/qr/dto/QrCheckDto.java
  src/main/java/zoo/insightnote/domain/qr/service/QrService.java
  src/main/java/zoo/insightnote/domain/reservation/entity/Reservation.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationRepository.java
  src/main/java/zoo/insightnote/domain/reservation/service/ReservationService.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
Labels: ✨ feat

#88 [#86] JWTFilter 로그인과 상관관계 없게 수정
  src/main/java/zoo/insightnote/global/config/SecurityConfig.java
  src/main/java/zoo/insightnote/global/jwt/JWTFilter.java
Labels: 🔨fix

#96 [#95] isOnline 삭제
  src/main/java/zoo/insightnote/domain/dummy/service/DummyUserService.java
Labels: 🔨fix

#94 [#33] Payment 리팩토링
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentControllerImpl.java
  src/main/java/zoo/insightnote/domain/payment/entity/Payment.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentRedisService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/user/entity/User.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
Labels: 🎨refactor

#100 build : 워크플로우 파일 분리 및 헬스체크 컨트롤러 추가
  .github/workflows/Dev-CICD.yml
  .github/workflows/Prod-CICD.yml
  build.gradle
  scripts/after_install.sh
  src/main/java/zoo/insightnote/domain/email/dto/request/EmailAuthRequest.java
  src/main/java/zoo/insightnote/domain/email/service/EmailService.java
  src/main/java/zoo/insightnote/domain/email/service/EmailVerificationService.java
  src/main/java/zoo/insightnote/domain/event/dto/req/EventRequestDto.java
  src/main/java/zoo/insightnote/domain/user/controller/UserController.java
  src/main/java/zoo/insightnote/domain/user/controller/UserControllerImpl.java
  src/main/java/zoo/insightnote/domain/user/dto/request/JoinDto.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
  src/main/java/zoo/insightnote/global/HealthCheck.java
  src/main/java/zoo/insightnote/global/config/CorsMvcConfig.java
  src/main/java/zoo/insightnote/global/config/SecurityConfig.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
  src/main/java/zoo/insightnote/global/jwt/GuestLoginFilter.java
  src/main/resources/application.yml
Labels: ⚙ build

#101 [#95] Payment, Reservation 더미 데이터 생성
  src/main/java/zoo/insightnote/domain/dummy/controller/DummyDataController.java
  src/main/java/zoo/insightnote/domain/dummy/controller/DummyDataControllerImpl.java
  src/main/java/zoo/insightnote/domain/dummy/data/PaymentDummyData.java
  src/main/java/zoo/insightnote/domain/dummy/service/DummyPaymentService.java
Labels: ✨ feat

#105 [#89] 비회원 회원가입과 로그인 api 하나로 통일
  src/main/java/zoo/insightnote/domain/email/service/EmailService.java
  src/main/java/zoo/insightnote/domain/email/service/EmailVerificationService.java
  src/main/java/zoo/insightnote/domain/user/controller/UserController.java
  src/main/java/zoo/insightnote/domain/user/controller/UserControllerImpl.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
  src/main/java/zoo/insightnote/global/config/SecurityConfig.java
  src/main/java/zoo/insightnote/global/jwt/GuestLoginFilter.java
Labels: ✨ feat

#114 [#110] 마이페이지 유저 정보 업데이트
  src/main/java/zoo/insightnote/domain/user/controller/UserController.java
  src/main/java/zoo/insightnote/domain/user/controller/UserControllerImpl.java
  src/main/java/zoo/insightnote/domain/user/dto/request/UserInfoRequest.java
  src/main/java/zoo/insightnote/domain/user/dto/response/PaymentUserInfoResponseDto.java
  src/main/java/zoo/insightnote/domain/user/dto/response/UserInfoResponse.java
  src/main/java/zoo/insightnote/domain/user/entity/User.java
  src/main/java/zoo/insightnote/domain/user/mapper/UserMapper.java
  src/main/java/zoo/insightnote/domain/user/service/CustomOAuth2UserService.java
  src/main/java/zoo/insightnote/domain/user/service/CustomUserDetailsService.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
  src/main/java/zoo/insightnote/global/jwt/GuestLoginFilter.java
  src/main/java/zoo/insightnote/global/oauth2/CustomSuccessHandler.java
  src/main/java/zoo/insightnote/global/oauth2/dto/CustomOAuth2User.java
  src/main/java/zoo/insightnote/global/oauth2/dto/CustomUserDetails.java
  src/main/java/zoo/insightnote/global/oauth2/dto/GoogleResponse.java
  src/main/java/zoo/insightnote/global/oauth2/dto/KakaoResponse.java
  src/main/java/zoo/insightnote/global/oauth2/dto/OAuth2Response.java
  src/main/java/zoo/insightnote/global/oauth2/dto/UserDto.java
Labels: ✨ feat, 🔨fix

#112 [#83] 카카오페이 결제 취소 서비스 구현
  src/main/java/zoo/insightnote/domain/payment/dto/etc/AmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/ApproveCancelAmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/CancelAvailableAmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/CanceledAmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentCancelRequestDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayCancelResponseDto.java
  src/main/java/zoo/insightnote/domain/payment/entity/Payment.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
Labels: ✨ feat

#119 [#113] 내 세션 리스트 API 구현
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentController.java
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentControllerImpl.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentRequestReadyDto.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/reservation/dto/response/UserTicketInfoResponseDto.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationCustomQueryRepository.java
Labels: ✨ feat

#123 [#118] 회원 탈퇴 로직
  src/main/java/zoo/insightnote/domain/user/controller/UserController.java
  src/main/java/zoo/insightnote/domain/user/controller/UserControllerImpl.java
  src/main/java/zoo/insightnote/domain/user/entity/User.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
Labels: ✨ feat

#124 [#122] Reservation, Payment 리팩토링
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentControllerImpl.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationRepository.java
  src/main/java/zoo/insightnote/domain/reservation/service/ReservationService.java
  src/main/java/zoo/insightnote/domain/session/entity/Session.java
  src/main/java/zoo/insightnote/domain/session/service/SessionService.java
  src/main/java/zoo/insightnote/global/exception/ErrorCode.java
Labels: ✨ feat, 🎨refactor

#128 [#127] 비회원에서 회원으로 전환 시 정보 연동
  src/main/java/zoo/insightnote/domain/dummy/service/DummyUserService.java
  src/main/java/zoo/insightnote/domain/user/entity/AuthProvider.java
  src/main/java/zoo/insightnote/domain/user/entity/User.java
  src/main/java/zoo/insightnote/domain/user/service/CustomOAuth2UserService.java
Labels: ✨ feat

#130 [#129] 온라인 신청 세션 인원 카운트 제외
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/reservation/service/ReservationService.java
Labels: 🔨fix

#131 [#126] 결제 성공 이메일 전송 기능 구현
  src/main/java/zoo/insightnote/domain/email/service/EmailService.java
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentController.java
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentControllerImpl.java
  src/main/java/zoo/insightnote/domain/payment/entity/Payment.java
  src/main/java/zoo/insightnote/domain/reservation/dto/response/UserTicketInfoResponseDto.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationCustomQueryRepository.java
Labels: ✨ feat

#134 [#133] 마이페이지 본인 정보 반환 시 username 추가
  src/main/java/zoo/insightnote/domain/user/controller/UserController.java
  src/main/java/zoo/insightnote/domain/user/dto/response/UserInfoResponse.java
  src/main/java/zoo/insightnote/domain/user/mapper/UserMapper.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
  src/main/java/zoo/insightnote/global/config/CorsMvcConfig.java
  src/main/java/zoo/insightnote/global/config/SecurityConfig.java
Labels: ✨ feat

#136 [#132] Payment, Reservation DTO 리팩토링
  src/main/java/zoo/insightnote/domain/email/dto/request/PaymentSuccessMailRequest.java
  src/main/java/zoo/insightnote/domain/email/dto/request/SessionSummary.java
  src/main/java/zoo/insightnote/domain/email/mapper/PaymentSuccessMailMapper.java
  src/main/java/zoo/insightnote/domain/email/service/EmailService.java
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentController.java
  src/main/java/zoo/insightnote/domain/payment/controller/PaymentControllerImpl.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/AmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/ApproveCancelAmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/CancelAvailableAmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/CanceledAmountDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/CardInfoDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/etc/UserInfoDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentApproveRequest.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentApproveRequestDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentCancelRequest.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentCancelRequestDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentReadyRequest.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/PaymentRequestReadyDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/request/UserInfo.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/Amount.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/ApproveCancelAmount.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/CancelAvailableAmount.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/CanceledAmount.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/CardInfo.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayApproveResponse.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayApproveResponseDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayCancelResponse.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayCancelResponseDto.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayReadyResponse.java
  src/main/java/zoo/insightnote/domain/payment/dto/response/KakaoPayReadyResponseDto.java
  src/main/java/zoo/insightnote/domain/payment/mapper/PaymentApproveMapper.java
  src/main/java/zoo/insightnote/domain/payment/mapper/PaymentCancelMapper.java
  src/main/java/zoo/insightnote/domain/payment/service/KakaoPayService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentRedisService.java
  src/main/java/zoo/insightnote/domain/payment/service/PaymentService.java
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationController.java
  src/main/java/zoo/insightnote/domain/reservation/controller/ReservationControllerImpl.java
  src/main/java/zoo/insightnote/domain/reservation/dto/response/ReservationSessions.java
  src/main/java/zoo/insightnote/domain/reservation/dto/response/UserTicketInfoResponse.java
  src/main/java/zoo/insightnote/domain/reservation/dto/response/UserTicketInfoResponseDto.java
  src/main/java/zoo/insightnote/domain/reservation/mapper/UserTicketInfoMapper.java
  src/main/java/zoo/insightnote/domain/reservation/repository/ReservationCustomQueryRepository.java
  src/main/java/zoo/insightnote/domain/reservation/service/ReservationService.java
  src/main/java/zoo/insightnote/domain/user/service/UserService.java
Labels: 🎨refactor

#139 [#138] QR 이미지 저장 경로 수정
  .github/workflows/Dev-CICD.yml
  scripts/after_install.sh
  src/main/java/zoo/insightnote/domain/qr/service/QrService.java
  src/main/resources/application.yml
Labels: 🔨fix
